68 navbar improvements
front-end-by-rimantas/42-grupe-portfolio-agar pull request #74
Opened 2023-02-12 18:42 UTC by RimasZ

2023-02-12 19:06 UTC, MonikaJaraite requested changes
Rimantai, nav-bar super!
Pažiūrėk, prašau, kitas dalis apačioje - nusimušė trys dalys - tekstų spalvos ir background'as

2023-02-12 19:18 UTC, RimasZ commented
pasitaisiau, net nežinau kaip jis ten nusimušė taip....

2023-02-12 19:55 UTC, MonikaJaraite approved these changes
Žemesnėse sekcijose viskas susitvarkė. 
Ir net žali ženkliukai sukasi! Rimantai - nerealiai! Net pagalvojau, kad originalią svetainę atsiverčiau 😄

2023-02-12 20:24 UTC, MonikaJaraite approved these changes
Trūksta tarpo tarp stulpelių - pamažinus ekraną liečiasi kampai:
![image](https://user-images.githubusercontent.com/121028511/218335108-0b87b191-cce4-43f3-a212-96f84de2e502.png)
Taip pat prieš mygtuką gerai būtų padding'as arba margin, nes jis "prilipęs" prie teksto. 
Ir dar lyg ir fonas nepilnai uždėtas, bet čia jau smulkmena.
Iš bėdos galima išblizginti vėliau, jei dar reikės 😄

2023-02-12 20:26 UTC, RimasZ commented
čia kaip ir ne mano sekcija berots? :D

2023-02-12 21:34 UTC, KriemiKat approved these changes
![image](https://user-images.githubusercontent.com/113378226/218338395-1cecdb3f-e612-4170-b62e-346ae3a057a8.png)
Viskas atrodo gerai!  Ateityje dar galima padaryti, kad navbar būtų matomas nuskrolinus žemyn.

2023-02-12 21:38 UTC, merged

2023-02-13 08:28 UTC, MonikaJaraite commented
> čia kaip ir ne mano sekcija berots? :D

Oi, isijauciau vakar - ne ten ikeliau matyt komentara :D