Footer to Development
front-end-by-rimantas/42-grupe-portfolio-agar pull request #77
Opened 2023-02-12 19:51 UTC by MonikaJaraite

Rimanto pull requesto dėka pamačiau, kaip reikia pavadinti ">" ženkliuką font-awesome šrifte :)
Ir iš to entuziazmo susitvarkiau list'ų hoverius.
Dabar jau pati nebematau, ką dar reikėtų taisyti :)

2023-02-12 20:08 UTC, RimasZ approved these changes

2023-02-12 21:22 UTC, KriemiKat approved these changes, later dismissed
Atrodo gerai

2023-02-13 06:20 UTC, RimasZ requested changes
Kažkodėl pas tave čia ant navbar rodiklyčių pridėliota, ir stiliai nusimušę...

2023-02-13 06:35 UTC, MonikaJaraite commented
Rimantai, tau su'merge'inus savo dali, pas mane buvo po approve'o atsirades konfliktas (nes mano branch'e dar buvo likusi tavo sena dalis). As konflikta sutvarkiau. Man rodo viska tvarkingai. Uzmesk, prasau, aki dar karta.

2023-02-13 06:39 UTC, MonikaJaraite commented
CSS'e pas mane visas stilius tik su .footer klasemis - realiai neturejo niekas nusimusti

2023-02-13 06:44 UTC, RimasZ commented
> CSS'e pas mane visas stilius tik su .footer klasemis - realiai neturejo niekas nusimusti navbar'e

![image](https://user-images.githubusercontent.com/17437550/218388950-a15a2817-cecb-449e-adaa-b7ba5121afb2.png)
Šita vieta index.html faile

2023-02-13 07:05 UTC, MonikaJaraite commented
Matyt per daug automatiskai iklijavusi buvau...
Pataisiau. Lyg ir dabar gerai :)

2023-02-13 07:07 UTC, RimasZ approved these changes

2023-02-13 08:37 UTC, KriemiKat approved these changes

2023-02-13 08:40 UTC, merged